/*
 * kennect-api
 * The Sterling On Demand API allows you to integrate background checks into your platform and manage the process form end-to-end.
 *
 * OpenAPI spec version: 2018-01-18T13:42:32.656-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A Candidate Address
 */
@ApiModel(description = "A Candidate Address")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-22T10:28:10.147-08:00")
public class Address {
  @SerializedName("addressLine")
  private String addressLine = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("municipality")
  private String municipality = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("regionCode")
  private String regionCode = null;

  public Address addressLine(String addressLine) {
    this.addressLine = addressLine;
    return this;
  }

   /**
   * The candidate&#39;s residential street address, such as \&quot;123 Main Street\&quot;
   * @return addressLine
  **/
  @ApiModelProperty(value = "The candidate's residential street address, such as \"123 Main Street\"")
  public String getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(String addressLine) {
    this.addressLine = addressLine;
  }

  public Address countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * the two-letter ISO short code for the country of the address, such as \&quot;US\&quot;
   * @return countryCode
  **/
  @ApiModelProperty(value = "the two-letter ISO short code for the country of the address, such as \"US\"")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public Address municipality(String municipality) {
    this.municipality = municipality;
    return this;
  }

   /**
   * the city or town of the address
   * @return municipality
  **/
  @ApiModelProperty(value = "the city or town of the address")
  public String getMunicipality() {
    return municipality;
  }

  public void setMunicipality(String municipality) {
    this.municipality = municipality;
  }

  public Address postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * the 5 or 9 digit zip code for the address, wth no dashes for US addresses.
   * @return postalCode
  **/
  @ApiModelProperty(value = "the 5 or 9 digit zip code for the address, wth no dashes for US addresses.")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public Address regionCode(String regionCode) {
    this.regionCode = regionCode;
    return this;
  }

   /**
   * the ISO 3166-2 region, such as a US state, where the candidate lives. In the US, this is the combination of \&quot;US\&quot;, a dash, and the state or territory&#39;s two-letter postal code. For example, Texas is \&quot;US-TX\&quot; and Puerto Rico is \&quot;US-PR\&quot;
   * @return regionCode
  **/
  @ApiModelProperty(value = "the ISO 3166-2 region, such as a US state, where the candidate lives. In the US, this is the combination of \"US\", a dash, and the state or territory's two-letter postal code. For example, Texas is \"US-TX\" and Puerto Rico is \"US-PR\"")
  public String getRegionCode() {
    return regionCode;
  }

  public void setRegionCode(String regionCode) {
    this.regionCode = regionCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.addressLine, address.addressLine) &&
        Objects.equals(this.countryCode, address.countryCode) &&
        Objects.equals(this.municipality, address.municipality) &&
        Objects.equals(this.postalCode, address.postalCode) &&
        Objects.equals(this.regionCode, address.regionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressLine, countryCode, municipality, postalCode, regionCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    municipality: ").append(toIndentedString(municipality)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    regionCode: ").append(toIndentedString(regionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

