/*
 * kennect-api
 * The Sterling On Demand API allows you to integrate background checks into your platform and manage the process form end-to-end.
 *
 * OpenAPI spec version: 2018-01-29T12:48:56.083-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AdverseActionRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T09:50:06.551-08:00")
public class AdverseActionRequest {
  @SerializedName("comment")
  private String comment = null;

  @SerializedName("reportItemIds")
  private List<String> reportItemIds = null;

  public AdverseActionRequest comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Text explaining the reason for the adverse action (not every item can take a reason)
   * @return comment
  **/
  @ApiModelProperty(value = "Text explaining the reason for the adverse action (not every item can take a reason)")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AdverseActionRequest reportItemIds(List<String> reportItemIds) {
    this.reportItemIds = reportItemIds;
    return this;
  }

  public AdverseActionRequest addReportItemIdsItem(String reportItemIdsItem) {
    if (this.reportItemIds == null) {
      this.reportItemIds = new ArrayList<String>();
    }
    this.reportItemIds.add(reportItemIdsItem);
    return this;
  }

   /**
   * List of report item ids that are involved with the adverse action
   * @return reportItemIds
  **/
  @ApiModelProperty(value = "List of report item ids that are involved with the adverse action")
  public List<String> getReportItemIds() {
    return reportItemIds;
  }

  public void setReportItemIds(List<String> reportItemIds) {
    this.reportItemIds = reportItemIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdverseActionRequest adverseActionRequest = (AdverseActionRequest) o;
    return Objects.equals(this.comment, adverseActionRequest.comment) &&
        Objects.equals(this.reportItemIds, adverseActionRequest.reportItemIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, reportItemIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdverseActionRequest {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    reportItemIds: ").append(toIndentedString(reportItemIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

