/*
 * kennect-api
 * The Sterling On Demand API allows you to integrate background checks into your platform and manage the process form end-to-end.
 *
 * OpenAPI spec version: 2018-01-18T13:42:32.656-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CandidatePortalLinkResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-22T10:28:10.147-08:00")
public class CandidatePortalLinkResponse {
  @SerializedName("candidatePortal")
  private String candidatePortal = null;

  public CandidatePortalLinkResponse candidatePortal(String candidatePortal) {
    this.candidatePortal = candidatePortal;
    return this;
  }

   /**
   * Get candidatePortal
   * @return candidatePortal
  **/
  @ApiModelProperty(value = "")
  public String getCandidatePortal() {
    return candidatePortal;
  }

  public void setCandidatePortal(String candidatePortal) {
    this.candidatePortal = candidatePortal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidatePortalLinkResponse candidatePortalLinkResponse = (CandidatePortalLinkResponse) o;
    return Objects.equals(this.candidatePortal, candidatePortalLinkResponse.candidatePortal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(candidatePortal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidatePortalLinkResponse {\n");
    
    sb.append("    candidatePortal: ").append(toIndentedString(candidatePortal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

