/*
 * kennect-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018-01-03T11:31:31.343-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CandidateAlias
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-12T12:11:57.321-08:00")
public class CandidateAlias {
  @SerializedName("confirmedNoMiddleName")
  private Boolean confirmedNoMiddleName = null;

  @SerializedName("familyName")
  private String familyName = null;

  @SerializedName("givenName")
  private String givenName = null;

  @SerializedName("middleName")
  private String middleName = null;

  public CandidateAlias confirmedNoMiddleName(Boolean confirmedNoMiddleName) {
    this.confirmedNoMiddleName = confirmedNoMiddleName;
    return this;
  }

   /**
   * Get confirmedNoMiddleName
   * @return confirmedNoMiddleName
  **/
  @ApiModelProperty(value = "")
  public Boolean getConfirmedNoMiddleName() {
    return confirmedNoMiddleName;
  }

  public void setConfirmedNoMiddleName(Boolean confirmedNoMiddleName) {
    this.confirmedNoMiddleName = confirmedNoMiddleName;
  }

  public CandidateAlias familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  @ApiModelProperty(value = "")
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public CandidateAlias givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  @ApiModelProperty(value = "")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public CandidateAlias middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @ApiModelProperty(value = "")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateAlias candidateAlias = (CandidateAlias) o;
    return Objects.equals(this.confirmedNoMiddleName, candidateAlias.confirmedNoMiddleName) &&
        Objects.equals(this.familyName, candidateAlias.familyName) &&
        Objects.equals(this.givenName, candidateAlias.givenName) &&
        Objects.equals(this.middleName, candidateAlias.middleName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmedNoMiddleName, familyName, givenName, middleName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateAlias {\n");
    
    sb.append("    confirmedNoMiddleName: ").append(toIndentedString(confirmedNoMiddleName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

