/*
 * kennect-api
 * The Sterling On Demand API allows you to integrate background checks into your platform and manage the process form end-to-end.
 *
 * OpenAPI spec version: 2018-01-17T10:44:23.086-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DriversLicense
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-17T11:27:12.738-08:00")
public class DriversLicense {
  @SerializedName("issuingAgency")
  private String issuingAgency = null;

  @SerializedName("licenseNumber")
  private String licenseNumber = null;

  @SerializedName("type")
  private String type = null;

  public DriversLicense issuingAgency(String issuingAgency) {
    this.issuingAgency = issuingAgency;
    return this;
  }

   /**
   * Get issuingAgency
   * @return issuingAgency
  **/
  @ApiModelProperty(value = "")
  public String getIssuingAgency() {
    return issuingAgency;
  }

  public void setIssuingAgency(String issuingAgency) {
    this.issuingAgency = issuingAgency;
  }

  public DriversLicense licenseNumber(String licenseNumber) {
    this.licenseNumber = licenseNumber;
    return this;
  }

   /**
   * Get licenseNumber
   * @return licenseNumber
  **/
  @ApiModelProperty(value = "")
  public String getLicenseNumber() {
    return licenseNumber;
  }

  public void setLicenseNumber(String licenseNumber) {
    this.licenseNumber = licenseNumber;
  }

  public DriversLicense type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DriversLicense driversLicense = (DriversLicense) o;
    return Objects.equals(this.issuingAgency, driversLicense.issuingAgency) &&
        Objects.equals(this.licenseNumber, driversLicense.licenseNumber) &&
        Objects.equals(this.type, driversLicense.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuingAgency, licenseNumber, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DriversLicense {\n");
    
    sb.append("    issuingAgency: ").append(toIndentedString(issuingAgency)).append("\n");
    sb.append("    licenseNumber: ").append(toIndentedString(licenseNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

