/*
 * kennect-api
 * The Sterling On Demand API allows you to integrate background checks into your platform and manage the process form end-to-end.
 *
 * OpenAPI spec version: 2018-01-17T10:44:23.086-08:00
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sts.oda.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
import sts.oda.client.model.AdverseActionResponse;
import sts.oda.client.model.CallbackResponse;
import sts.oda.client.model.Dispute;
import sts.oda.client.model.Invite;
import sts.oda.client.model.ReferenceCode;
import sts.oda.client.model.ScreeningResponseLink;
import sts.oda.client.model.ScreeningResponseReportItem;

/**
 * ScreeningResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-18T09:55:21.026-08:00")
public class ScreeningResponse {
  @SerializedName("adverseActions")
  private List<AdverseActionResponse> adverseActions = null;

  @SerializedName("billingCode")
  private String billingCode = null;

  @SerializedName("callback")
  private CallbackResponse callback = null;

  @SerializedName("candidateId")
  private String candidateId = null;

  @SerializedName("clientCriteriaResult")
  private String clientCriteriaResult = null;

  @SerializedName("dispute")
  private Dispute dispute = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("invite")
  private Invite invite = null;

  @SerializedName("links")
  private ScreeningResponseLink links = null;

  @SerializedName("packageId")
  private String packageId = null;

  @SerializedName("referenceCodes")
  private List<ReferenceCode> referenceCodes = null;

  @SerializedName("reportItems")
  private List<ScreeningResponseReportItem> reportItems = null;

  @SerializedName("result")
  private String result = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("submittedAt")
  private DateTime submittedAt = null;

  @SerializedName("trustedUserId")
  private String trustedUserId = null;

  @SerializedName("updatedAt")
  private DateTime updatedAt = null;

  public ScreeningResponse adverseActions(List<AdverseActionResponse> adverseActions) {
    this.adverseActions = adverseActions;
    return this;
  }

  public ScreeningResponse addAdverseActionsItem(AdverseActionResponse adverseActionsItem) {
    if (this.adverseActions == null) {
      this.adverseActions = new ArrayList<AdverseActionResponse>();
    }
    this.adverseActions.add(adverseActionsItem);
    return this;
  }

   /**
   * Get adverseActions
   * @return adverseActions
  **/
  @ApiModelProperty(value = "")
  public List<AdverseActionResponse> getAdverseActions() {
    return adverseActions;
  }

  public void setAdverseActions(List<AdverseActionResponse> adverseActions) {
    this.adverseActions = adverseActions;
  }

  public ScreeningResponse billingCode(String billingCode) {
    this.billingCode = billingCode;
    return this;
  }

   /**
   * Get billingCode
   * @return billingCode
  **/
  @ApiModelProperty(value = "")
  public String getBillingCode() {
    return billingCode;
  }

  public void setBillingCode(String billingCode) {
    this.billingCode = billingCode;
  }

  public ScreeningResponse callback(CallbackResponse callback) {
    this.callback = callback;
    return this;
  }

   /**
   * Get callback
   * @return callback
  **/
  @ApiModelProperty(value = "")
  public CallbackResponse getCallback() {
    return callback;
  }

  public void setCallback(CallbackResponse callback) {
    this.callback = callback;
  }

  public ScreeningResponse candidateId(String candidateId) {
    this.candidateId = candidateId;
    return this;
  }

   /**
   * Get candidateId
   * @return candidateId
  **/
  @ApiModelProperty(value = "")
  public String getCandidateId() {
    return candidateId;
  }

  public void setCandidateId(String candidateId) {
    this.candidateId = candidateId;
  }

  public ScreeningResponse clientCriteriaResult(String clientCriteriaResult) {
    this.clientCriteriaResult = clientCriteriaResult;
    return this;
  }

   /**
   * Get clientCriteriaResult
   * @return clientCriteriaResult
  **/
  @ApiModelProperty(value = "")
  public String getClientCriteriaResult() {
    return clientCriteriaResult;
  }

  public void setClientCriteriaResult(String clientCriteriaResult) {
    this.clientCriteriaResult = clientCriteriaResult;
  }

  public ScreeningResponse dispute(Dispute dispute) {
    this.dispute = dispute;
    return this;
  }

   /**
   * Get dispute
   * @return dispute
  **/
  @ApiModelProperty(value = "")
  public Dispute getDispute() {
    return dispute;
  }

  public void setDispute(Dispute dispute) {
    this.dispute = dispute;
  }

  public ScreeningResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ScreeningResponse invite(Invite invite) {
    this.invite = invite;
    return this;
  }

   /**
   * Get invite
   * @return invite
  **/
  @ApiModelProperty(value = "")
  public Invite getInvite() {
    return invite;
  }

  public void setInvite(Invite invite) {
    this.invite = invite;
  }

  public ScreeningResponse links(ScreeningResponseLink links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public ScreeningResponseLink getLinks() {
    return links;
  }

  public void setLinks(ScreeningResponseLink links) {
    this.links = links;
  }

  public ScreeningResponse packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Get packageId
   * @return packageId
  **/
  @ApiModelProperty(value = "")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public ScreeningResponse referenceCodes(List<ReferenceCode> referenceCodes) {
    this.referenceCodes = referenceCodes;
    return this;
  }

  public ScreeningResponse addReferenceCodesItem(ReferenceCode referenceCodesItem) {
    if (this.referenceCodes == null) {
      this.referenceCodes = new ArrayList<ReferenceCode>();
    }
    this.referenceCodes.add(referenceCodesItem);
    return this;
  }

   /**
   * Get referenceCodes
   * @return referenceCodes
  **/
  @ApiModelProperty(value = "")
  public List<ReferenceCode> getReferenceCodes() {
    return referenceCodes;
  }

  public void setReferenceCodes(List<ReferenceCode> referenceCodes) {
    this.referenceCodes = referenceCodes;
  }

  public ScreeningResponse reportItems(List<ScreeningResponseReportItem> reportItems) {
    this.reportItems = reportItems;
    return this;
  }

  public ScreeningResponse addReportItemsItem(ScreeningResponseReportItem reportItemsItem) {
    if (this.reportItems == null) {
      this.reportItems = new ArrayList<ScreeningResponseReportItem>();
    }
    this.reportItems.add(reportItemsItem);
    return this;
  }

   /**
   * Get reportItems
   * @return reportItems
  **/
  @ApiModelProperty(value = "")
  public List<ScreeningResponseReportItem> getReportItems() {
    return reportItems;
  }

  public void setReportItems(List<ScreeningResponseReportItem> reportItems) {
    this.reportItems = reportItems;
  }

  public ScreeningResponse result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public ScreeningResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ScreeningResponse submittedAt(DateTime submittedAt) {
    this.submittedAt = submittedAt;
    return this;
  }

   /**
   * Get submittedAt
   * @return submittedAt
  **/
  @ApiModelProperty(value = "")
  public DateTime getSubmittedAt() {
    return submittedAt;
  }

  public void setSubmittedAt(DateTime submittedAt) {
    this.submittedAt = submittedAt;
  }

  public ScreeningResponse trustedUserId(String trustedUserId) {
    this.trustedUserId = trustedUserId;
    return this;
  }

   /**
   * Get trustedUserId
   * @return trustedUserId
  **/
  @ApiModelProperty(value = "")
  public String getTrustedUserId() {
    return trustedUserId;
  }

  public void setTrustedUserId(String trustedUserId) {
    this.trustedUserId = trustedUserId;
  }

  public ScreeningResponse updatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public DateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(DateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreeningResponse screeningResponse = (ScreeningResponse) o;
    return Objects.equals(this.adverseActions, screeningResponse.adverseActions) &&
        Objects.equals(this.billingCode, screeningResponse.billingCode) &&
        Objects.equals(this.callback, screeningResponse.callback) &&
        Objects.equals(this.candidateId, screeningResponse.candidateId) &&
        Objects.equals(this.clientCriteriaResult, screeningResponse.clientCriteriaResult) &&
        Objects.equals(this.dispute, screeningResponse.dispute) &&
        Objects.equals(this.id, screeningResponse.id) &&
        Objects.equals(this.invite, screeningResponse.invite) &&
        Objects.equals(this.links, screeningResponse.links) &&
        Objects.equals(this.packageId, screeningResponse.packageId) &&
        Objects.equals(this.referenceCodes, screeningResponse.referenceCodes) &&
        Objects.equals(this.reportItems, screeningResponse.reportItems) &&
        Objects.equals(this.result, screeningResponse.result) &&
        Objects.equals(this.status, screeningResponse.status) &&
        Objects.equals(this.submittedAt, screeningResponse.submittedAt) &&
        Objects.equals(this.trustedUserId, screeningResponse.trustedUserId) &&
        Objects.equals(this.updatedAt, screeningResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adverseActions, billingCode, callback, candidateId, clientCriteriaResult, dispute, id, invite, links, packageId, referenceCodes, reportItems, result, status, submittedAt, trustedUserId, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreeningResponse {\n");
    
    sb.append("    adverseActions: ").append(toIndentedString(adverseActions)).append("\n");
    sb.append("    billingCode: ").append(toIndentedString(billingCode)).append("\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    candidateId: ").append(toIndentedString(candidateId)).append("\n");
    sb.append("    clientCriteriaResult: ").append(toIndentedString(clientCriteriaResult)).append("\n");
    sb.append("    dispute: ").append(toIndentedString(dispute)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invite: ").append(toIndentedString(invite)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    referenceCodes: ").append(toIndentedString(referenceCodes)).append("\n");
    sb.append("    reportItems: ").append(toIndentedString(reportItems)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    submittedAt: ").append(toIndentedString(submittedAt)).append("\n");
    sb.append("    trustedUserId: ").append(toIndentedString(trustedUserId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

